[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
<<<<<<< HEAD
=======

upload_port = /dev/cu.usbserial-CD528D1439
monitor_port = /dev/cu.usbserial-CD528D1439
>>>>>>> main
monitor_speed = 115200

lib_deps =
  m5stack/M5Atom
<<<<<<< HEAD
  fastled/FastLED
  h2zero/NimBLE-Arduino
=======
  h2zero/NimBLE-Arduino
  fastled/FastLED
>>>>>>> main
